services:
  app:
    build: .

    ports:
      - "5000:3000"

    environment:
      DB_USER: ${DB_USER}

      DB_PASSWORD: ${DB_PASSWORD}

      DB_NAME: ${DB_NAME}

    depends_on:
      - mongo

  mongo:
    image: mongo:7

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
